### ISSUE TITLE
detection_custom.py does not work: issue: label = "{}".format(NUM_CLASS[class_ind]) + score_str KeyError: 1

### ISSUE THREAD

**Issue by chrisTopp84** [pythonlessons/TensorFlow-2.x-YOLOv3#102]
Hi,

I try to run detection_custom.py. Unfortunately the following error occurs:

  ```
nvidia@nvidia-desktop:~/Downloads/Mod1_TensorFlow-2.x-YOLOv3$ python3 detection_custom.py 
2020-11-27 20:52:57.228904: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-27 20:53:06.520579: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-11-27 20:53:06.527535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.527697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1742] Found device 0 with properties: 
pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 194.55MiB/s
2020-11-27 20:53:06.527826: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-27 20:53:06.551291: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2020-11-27 20:53:06.573612: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-27 20:53:06.611643: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-27 20:53:06.630139: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2020-11-27 20:53:06.648340: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2020-11-27 20:53:06.650022: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-11-27 20:53:06.650480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.651077: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.651212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1884] Adding visible gpu devices: 0
GPUs [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2020-11-27 20:53:06.765036: W tensorflow/core/platform/profile_utils/cpu_utils.cc:108] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency
2020-11-27 20:53:06.765703: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x66e7a80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-27 20:53:06.765763: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-27 20:53:06.856699: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.856992: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x54f0140 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-27 20:53:06.857047: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2020-11-27 20:53:06.857573: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.857689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1742] Found device 0 with properties: 
pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 194.55MiB/s
2020-11-27 20:53:06.857874: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-27 20:53:06.857995: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2020-11-27 20:53:06.858088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-27 20:53:06.858165: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-27 20:53:06.858239: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2020-11-27 20:53:06.858315: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2020-11-27 20:53:06.858390: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-11-27 20:53:06.858655: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.858930: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:06.858998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1884] Adding visible gpu devices: 0
2020-11-27 20:53:06.859128: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
2020-11-27 20:53:10.040630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1283] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-27 20:53:10.040721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1289]      0 
2020-11-27 20:53:10.040755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1302] 0:   N 
2020-11-27 20:53:10.041317: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:10.041685: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:949] ARM64 does not support NUMA - returning NUMA node zero
2020-11-27 20:53:10.041836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1428] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1009 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
2020-11-27 20:53:18.228644: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-11-27 20:53:24.423165: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2020-11-27 20:53:29.455043: W tensorflow/core/common_runtime/bfc_allocator.cc:246] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Time: 16360.03ms, Detection FPS: 0.1, total FPS: 0.1
Time: 8469.52ms, Detection FPS: 0.1, total FPS: 0.1
Time: 5736.25ms, Detection FPS: 0.2, total FPS: 0.2
Time: 4370.41ms, Detection FPS: 0.2, total FPS: 0.2
Traceback (most recent call last):
  File "detection_custom.py", line 24, in <module>
    detect_video(yolo, video_path, './IMAGES/pedestrians.mp4', input_size=YOLO_INPUT_SIZE, show=False, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
  File "/home/nvidia/Downloads/Mod1_TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 470, in detect_video
    image = draw_bbox(original_image, bboxes, CLASSES=CLASSES, rectangle_colors=rectangle_colors)
  File "/home/nvidia/Downloads/Mod1_TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 157, in draw_bbox
    label = "{}".format(NUM_CLASS[class_ind]) + score_str
KeyError: 1
```
As you can see the detection starts and runs for a very short time until the error occurs.

I trained my model for only 4 epochs... I just wanted to learn the workflow. Therefore the performance of the model was not important to me. Maybe this is relevant in some way.

Any idea what I could do?

Thanks in advance and best regards
chris

**Comment by pythonlessons** [comment]
It's a problem with your configurations file, more specifically with the classes file. Check your configurations file
