### ISSUE TITLE
Problem train.py

### ISSUE THREAD

**Issue by voltea** [pythonlessons/TensorFlow-2.x-YOLOv3#113]
Hello how are you, I loved your tutorials, I am a newbie who is trying to create the custom train, everything is fine but when I run train.py I have the following errors

`configure TEST options to validate model`

and at the end I have the following:

`Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 185, in main
    mAP_model.load_weights(save_directory) # use keras weights
UnboundLocalError: local variable 'save_directory' referenced before assignment`

can you help me please
Thx

**Comment by voltea** [comment]
My problem had not generated the txt
