### ISSUE TITLE
Custom Tiny Yolov4 execution problem

### ISSUE THREAD

**Issue by cpraschl** [pythonlessons/TensorFlow-2.x-YOLOv3#121]
I have trained a custom tiny YoloV4. While the training was successful, the execution using `detection_custom.py` ends with:

``` 
Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x0000028318341108> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x0000028322165448>).
Traceback (most recent call last):
  File "...\TensorFlow-2.x-YOLOv3\detection_custom.py", line 26, in <module>
    yolo = Load_Yolo_model()
  File "...\TensorFlow-2.x-YOLOv3\yolov3\utils.py", line 94, in Load_Yolo_model
    yolo.load_weights(f"./checkpoints/{TRAIN_MODEL_NAME}") # use custom weights
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2182, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1320, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 914, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\tracking\util.py", line 297, in restore_saveables
    validated_saveables).restore(self.save_path_tensor, self.options)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\saving\functional_saver.py", line 340, in restore
    restore_ops = restore_fn()
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\saving\functional_saver.py", line 316, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\saving\functional_saver.py", line 111, in restore
    restored_tensors, restored_shapes=None)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 127, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 311, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "...\TensorFlow-2.x-YOLOv3\venv\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (128,) and (64,) are incompatible
```

Resulting weights file after training:
[yolov4-tiny.zip](https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/files/5782342/yolov4-tiny.zip)

The used class file currenlty only contains one class: log

Used version:
- TensorFlow-2.x-YOLOv3 Master (07.01.2021)
- tensorflow==2.3.1
- tensorflow-gpu==2.3.1
- opencv-python==4.1.2.30

I have also trained a classic, custom Yolov4 that works fine.

**Comment by cpraschl** [comment]
The problem is the name of the checkpoint that should be loaded in `utils.py`.
Since `train.py` adds a `_Train`  postfix to the model file, that is not considered in `utils.py`, the model can't be loaded. I had a left over classic Yolov4 model in the folder, so `utils.py` loaded this one, but used the wrong configs.

Can be solved by adapting `Load_Yolo_model()` in `utils.py`:

```python
def Load_Yolo_model():
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if len(gpus) > 0:
        print(f'GPUs {gpus}')
        try: tf.config.experimental.set_memory_growth(gpus[0], True)
        except RuntimeError: pass
        
    if YOLO_FRAMEWORK == "tf": # TensorFlow detection
        if YOLO_TYPE == "yolov4":
            Darknet_weights = YOLO_V4_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V4_WEIGHTS
        if YOLO_TYPE == "yolov3":
            Darknet_weights = YOLO_V3_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V3_WEIGHTS

        if YOLO_CUSTOM_WEIGHTS == False:
            yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=YOLO_COCO_CLASSES)
            load_yolo_weights(yolo, Darknet_weights)  # use Darknet weights
        else:
            yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
            ### Start of changes -----------------------------------------------------------------
            checkpoint = f"./checkpoints/{TRAIN_MODEL_NAME}"
            if TRAIN_YOLO_TINY:
                checkpoint += "_Tiny"
            yolo.load_weights(checkpoint)  # use custom weights
            ### End of changes -------------------------------------------------------------------
        
    elif YOLO_FRAMEWORK == "trt": # TensorRT detection
        saved_model_loaded = tf.saved_model.load(YOLO_CUSTOM_WEIGHTS, tags=[tag_constants.SERVING])
        signature_keys = list(saved_model_loaded.signatures.keys())
        yolo = saved_model_loaded.signatures['serving_default']

    return yolo
```

**Comment by pythonlessons** [comment]
Thanks, no one noticed this, I updated my code with your modification. Thanks!
