### ISSUE TITLE
"urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!" error

### ISSUE THREAD

**Issue by dbzkakarot13** [pythonlessons/TensorFlow-2.x-YOLOv3#136]
Hello I followed the following tutorial:
https://pylessons.com/YOLOv3-TF2-RaspberryPi/
I am running a raspberry pi 3b+
Everything seemed to be fine until the very end when I was trying to run the demo.  This is the error I received: 

pi@raspberrypi:~/Desktop/TensorFlow-2.x-YOLOv3 $ python detection_demo.py       /usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Loading Darknet_weights from: model_data/yolov3-tiny.weights
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Loading Darknet_weights from: model_data/yolov3-tiny.weights
Killed

Thank you,

**Comment by yassertest100** [comment]
same issue 
 python3 detection_demo.py
Loading Darknet_weights from: model_data/yolov3-tiny.weights
Traceback (most recent call last):
  File "detection_demo.py", line 22, in <module>
    yolo = Load_Yolo_model()
  File "/home/pi/Desktop/TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 92, in Load_Yolo_model
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
  File "/home/pi/Desktop/TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 33, in load_yolo_weights
    major, minor, revision, seen, _ = np.fromfile(wf, dtype=np.int32, count=5)
ValueError: not enough values to unpack (expected 5, got 0)

do you find any solution...
