### ISSUE TITLE
ValueError: could not broadcast input array from shape (411,416,3) into shape (416,416,3)

### ISSUE THREAD

**Issue by mehdi-salehi** [pythonlessons/TensorFlow-2.x-YOLOv3#18]
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 133, in main
    for image_data, target in trainset:
  File "C:\Users\Administrator\Desktop\TensorFlow-2.x-YOLOv3-master\yolov3\dataset.py", line 122, in __next__
    batch_image[num, :, :, :] = image
ValueError: could not broadcast input array from shape (411,416,3) into shape (416,416,3)

**Comment by pythonlessons** [comment]
what you tried?

**Comment by pythonlessons** [comment]
Fixed
