### ISSUE TITLE
Duplicate node name in graph "ones"

### ISSUE THREAD

**Issue by Quest2GM** [pythonlessons/TensorFlow-2.x-YOLOv3#37]
2020-08-19 12:52:07.347401: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'ones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_tracker.py", line 34, in <module>
    yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)
  File "C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 391, in Create_Yolo
    pred_tensor = decode(conv_tensor, NUM_CLASS, i)
  File "C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 420, in decode
    xy_grid = tf.meshgrid(tf.range(output_size), tf.range(output_size))
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2954, in meshgrid
    mult_fact = ones(shapes, output_dtype)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2583, in ones
    output = fill(shape, constant(one, dtype=dtype), name=name)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 171, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 3601, in fill
    "Fill", dims=dims, value=value, name=name)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 548, in create_op
    compute_device)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1773, in __init__
    control_input_ops)
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'ones'

Do you know a possible reason for this error when trying to run object_tracker.py? The error seems to be with Create_Yolo function in yolov4.py.

Also instead of using TensorFlow 2.2, I am using TensorFlow 2.0 since TensorFlow 2.2 kept giving me a DLL Import Error.

**Comment by pythonlessons** [comment]
YOLOv4 doesn't work with TF2.0, you can try installing 2.3, maybe you won't get DLL error.

**Comment by Quest2GM** [comment]
Really appreciated for your quick reply!

I am now getting this error:

2020-08-19 13:41:58.266852: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "detection_demo.py", line 33, in <module>
    detect_image(yolo, image_path, "./IMAGES/kite_pred.jpg", input_size=YOLO_INPUT_SIZE, show=True, rectangle_colors=(255,0,0))
  File "C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 645, in detect_image
    pred_bbox = YoloV3.predict(image_data)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 722, in predict
    callbacks=callbacks)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 565, in _make_execution_function
    return model._make_execution_function(mode)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2190, in _make_execution_function
    self._make_predict_function()
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2180, in _make_predict_function
    **kwargs)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3773, in function
    return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
  File "C:\Users\sid_a\anaconda3\envs\aps360\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3657, in __init__
    raise ValueError('Unknown graph. Aborting.')
ValueError: Unknown graph. Aborting.

(aps360) C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master>activate pytorch

(aps360) C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master>conda.bat activate pytorch

(pytorch) C:\Users\sid_a\PycharmProjects\MTO_Highway_Analysis\TensorFlow-2.x-YOLOv3-master>python detection_demo.py
Traceback (most recent call last):
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detection_demo.py", line 15, in <module>
    import tensorflow as tf
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\sid_a\anaconda3\envs\pytorch\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.


When I did more research, I found it depends on your version of CUDA. What CUDA version do you have?

**Comment by huunhan312** [comment]
@Quest2GM  I got same problem with you when I run YOLOv4 with TF2.1. However, I succeeded with run YOLOv4. I think you should make a dedicated environment as requirements.txt. 

@pythonlessons  Thank you for your work !

**Comment by Quest2GM** [comment]
The import DLL error was fixed by simply doing this: https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-573464774

Thank you @huunhan312 and @pythonlessons for your help, and kudos to @pythonlessons for the amazing program!

**Comment by arya46** [comment]
Both YOLOv3 and YOLOv4 throws this error 'Duplicate node name in graph "ones"' when I run it on my local machine.
I used both TF 2.1 and TF 2.2.

**Comment by Quest2GM** [comment]
Hey @arya46,

Try creating a new environment, and then pip install requirements.txt. Then try running the program. If that doesn't work, see if using TF 2.3 works.

Let me know if you are still getting the graph error.

**Comment by arya46** [comment]
@Quest2GM Hi, the model works perfectly fine with TF2.3. Maybe you should update the requirements.txt file

**Comment by chrisTopp84** [comment]
Hi,

I do not really know if it is possible to answer to a closed issue so I give it a try :)

I also get this error 

> ValueError: Duplicate node name in graph: 'ones'

I'm using a Jetson Nano with Jetpack 4.3. This Jetpack version is only compatible with TF 2.1.0 or lower. The version I use is TF 2.1.0.
TF 2.2 or TF 2.3 are not compatible with Jetpack 4.3.  
https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform-release-notes/tf-jetson-rel.html#tf-jetson-rel

Is there a possibility to solve the problem without changing the TF version to 2.2 or 2.3?
