### ISSUE TITLE
conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0]) ValueError: cannot reshape array

### ISSUE THREAD

**Issue by zubeyirgenc** [pythonlessons/TensorFlow-2.x-YOLOv3#39]
```
Traceback (most recent call last):
  File "detection_demo.py", line 31, in <module>
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
  File "/content/drive/My Drive/TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 68, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 391694 into shape (512,256,3,3)
```

I train a yolov3 model but in detection_demo.py give an error. This error occur in load yolov3.weights file. Take numbers that inside the model but in last layer the remaining numbers size is not equal to last layers size. I did not any changes in model file except traning changes.

**Comment by pythonlessons** [comment]
Can you give me your configs.py file, will test it

**Comment by zubeyirgenc** [comment]
```
`#================================================================
#
#   File name   : configs.py
#   Author      : PyLessons
#   Created date: 2020-08-18
#   Website     : https://pylessons.com/
#   GitHub      : https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3
#   Description : yolov3 configuration file
#
#================================================================

# YOLO options
YOLO_TYPE                   = "yolov3" # yolov4 or yolov3
YOLO_FRAMEWORK              = "tf" # "tf" or "trt"
YOLO_V3_WEIGHTS             = "model_data/yolov3.weights"
YOLO_V4_WEIGHTS             = "model_data/yolov4.weights"
YOLO_V3_TINY_WEIGHTS        = "model_data/yolov3-tiny.weights"
YOLO_V4_TINY_WEIGHTS        = "model_data/yolov4-tiny.weights"
YOLO_TRT_QUANTIZE_MODE      = "INT8" # INT8, FP16, FP32
YOLO_CUSTOM_WEIGHTS         = True # "checkpoints/yolov3_custom" # used in evaluate_mAP.py, if not using leave False
                            # YOLO_CUSTOM_WEIGHTS also used with TensorRT and custom model detection
YOLO_COCO_CLASSES           = "model_data/coco/coco.names"
YOLO_STRIDES                = [8, 16, 32]
YOLO_IOU_LOSS_THRESH        = 0.5
YOLO_ANCHOR_PER_SCALE       = 3
YOLO_MAX_BBOX_PER_SCALE     = 100
YOLO_INPUT_SIZE             = 416
if YOLO_TYPE                == "yolov4":
    YOLO_ANCHORS            = [[[12,  16], [19,   36], [40,   28]],
                               [[36,  75], [76,   55], [72,  146]],
                               [[142,110], [192, 243], [459, 401]]]
if YOLO_TYPE                == "yolov3":
    YOLO_ANCHORS            = [[[10,  13], [16,   30], [33,   23]],
                               [[30,  61], [62,   45], [59,  119]],
                               [[116, 90], [156, 198], [373, 326]]]
# Train options
TRAIN_YOLO_TINY             = False
TRAIN_SAVE_BEST_ONLY        = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT       = True # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES               = "model_data/license_plate_names.txt"
TRAIN_ANNOT_PATH            = "model_data/license_plate_train.txt"
TRAIN_LOGDIR                = "log"
TRAIN_CHECKPOINTS_FOLDER    = "checkpoints"
TRAIN_MODEL_NAME            = f"{YOLO_TYPE}_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = False # faster training, but need more RAM
TRAIN_BATCH_SIZE            = 8
TRAIN_INPUT_SIZE            = 416
TRAIN_DATA_AUG              = True
TRAIN_TRANSFER              = True
TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT               = 1e-4
TRAIN_LR_END                = 1e-6
TRAIN_WARMUP_EPOCHS         = 2
TRAIN_EPOCHS                = 5000

# TEST options
TEST_ANNOT_PATH             = "model_data/license_plate_test.txt"
TEST_BATCH_SIZE             = 4
TEST_INPUT_SIZE             = 416
TEST_DATA_AUG               = False
TEST_DECTECTED_IMAGE_PATH   = ""
TEST_SCORE_THRESHOLD        = 0.3
TEST_IOU_THRESHOLD          = 0.45


#YOLOv3-TINY and YOLOv4-TINY WORKAROUND
if TRAIN_YOLO_TINY:
    YOLO_STRIDES            = [16, 32, 64]    
    YOLO_ANCHORS            = [[[10,  14], [23,   27], [37,   58]],
                               [[81,  82], [135, 169], [344, 319]],
                               [[0,    0], [0,     0], [0,     0]]]
`
```

**Comment by zubeyirgenc** [comment]
```
864
(32, 3, 3, 3)
864

18432
(64, 32, 3, 3)
18432

2048
(32, 64, 1, 1)
2048

18432
(64, 32, 3, 3)
18432

73728
(128, 64, 3, 3)
73728

8192
(64, 128, 1, 1)
8192

73728
(128, 64, 3, 3)
73728

8192
(64, 128, 1, 1)
8192

73728
(128, 64, 3, 3)
73728

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

32768
(128, 256, 1, 1)
32768

294912
(256, 128, 3, 3)
294912

1179648
(512, 256, 3, 3)
1179648

131072
(256, 512, 1, 1)
131072

1179648
(512, 256, 3, 3)
1179648

131072
(256, 512, 1, 1)
131072

1179648
(512, 256, 3, 3)
1179648

131072
(256, 512, 1, 1)
131072

1179648
(512, 256, 3, 3)
1179648

131072
(256, 512, 1, 1)
131072

1179648
(512, 256, 3, 3)
391694

```
It is the output in every step. First line is np.product(conv_shape), second is conv_shape, third is np.size(conv_weights) in utils.py. In last step numbers is not equal so reshape function is not working.

**Comment by pythonlessons** [comment]
As I see the following line:
YOLO_CUSTOM_WEIGHTS         = True # "checkpoints/yolov3_custom"
You are trying to use custom weights, do you?
Because if yes, you should leave file path instead of True, otherwise leave False

**Comment by pythonlessons** [comment]
No reply
