### ISSUE TITLE
ValueError: Shapes (255,) and (18,) are incompatible

### ISSUE THREAD

**Issue by bedna-KU** [pythonlessons/TensorFlow-2.x-YOLOv3#44]
I train YOLOv3-Tiny on own dataset all work OK.

But if I run **python3 detection_custom.py** throw this error:
```
Traceback (most recent call last):
  File "detection_custom.py", line 31, in <module>
    yolo.load_weights(YOLO_CUSTOM_WEIGHTS) # use custom weights
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2182, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1320, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 914, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 297, in restore_saveables
    validated_saveables).restore(self.save_path_tensor, self.options)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 340, in restore
    restore_ops = restore_fn()
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 316, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 111, in restore
    restored_tensors, restored_shapes=None)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 127, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 311, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/mario/.local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (255,) and (18,) are incompatible
```
Config:
```
# YOLO options
YOLO_TYPE                   = "yolov3" # yolov4 or yolov3
YOLO_FRAMEWORK              = "tf" # "tf" or "trt"
YOLO_V3_WEIGHTS             = "model_data/yolov3.weights"
YOLO_V4_WEIGHTS             = "model_data/yolov4.weights"
YOLO_V3_TINY_WEIGHTS        = "model_data/yolov3-tiny.weights"
YOLO_V4_TINY_WEIGHTS        = "model_data/yolov4-tiny.weights"
YOLO_TRT_QUANTIZE_MODE      = "INT8" # INT8, FP16, FP32
YOLO_CUSTOM_WEIGHTS         = "checkpoints/yolov3_custom_Tiny" # "checkpoints/yolov3_custom" # used in evaluate_mAP.py and custom model detection, if not using leave False
                            # YOLO_CUSTOM_WEIGHTS also used with TensorRT and custom model detection
YOLO_COCO_CLASSES           = "model_data/coco/coco.names"
YOLO_STRIDES                = [8, 16, 32]
YOLO_IOU_LOSS_THRESH        = 0.5
YOLO_ANCHOR_PER_SCALE       = 3
YOLO_MAX_BBOX_PER_SCALE     = 100
YOLO_INPUT_SIZE             = 416
if YOLO_TYPE                == "yolov4":
    YOLO_ANCHORS            = [[[12,  16], [19,   36], [40,   28]],
                               [[36,  75], [76,   55], [72,  146]],
                               [[142,110], [192, 243], [459, 401]]]
if YOLO_TYPE                == "yolov3":
    YOLO_ANCHORS            = [[[10,  13], [16,   30], [33,   23]],
                               [[30,  61], [62,   45], [59,  119]],
                               [[116, 90], [156, 198], [373, 326]]]
# Train options
TRAIN_YOLO_TINY             = True
TRAIN_SAVE_BEST_ONLY        = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT       = False # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES               = "tools/dataset/list.names"
TRAIN_ANNOT_PATH            = "tools/dataset/list_train.txt"
TRAIN_LOGDIR                = "log"
TRAIN_CHECKPOINTS_FOLDER    = "checkpoints"
TRAIN_MODEL_NAME            = f"{YOLO_TYPE}_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = True # With True faster training, but need more RAM
TRAIN_BATCH_SIZE            = 4
TRAIN_INPUT_SIZE            = 416
TRAIN_DATA_AUG              = True
TRAIN_TRANSFER              = False
TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT               = 1e-4
TRAIN_LR_END                = 1e-6
TRAIN_WARMUP_EPOCHS         = 2
TRAIN_EPOCHS                = 3

# TEST options
TEST_ANNOT_PATH             = "tools/dataset/list_test.txt"
TEST_BATCH_SIZE             = 4
TEST_INPUT_SIZE             = 416
TEST_DATA_AUG               = False
TEST_DECTECTED_IMAGE_PATH   = ""
TEST_SCORE_THRESHOLD        = 0.3
TEST_IOU_THRESHOLD          = 0.45


#YOLOv3-TINY and YOLOv4-TINY WORKAROUND
if TRAIN_YOLO_TINY:
    YOLO_STRIDES            = [16, 32, 64]    
    YOLO_ANCHORS            = [[[10,  14], [23,   27], [37,   58]],
                               [[81,  82], [135, 169], [344, 319]],
                               [[0,    0], [0,     0], [0,     0]]]
```

**Comment by pythonlessons** [comment]
You sure you have three files in the checkpoints folder with the names yolov3_custom_Tiny... ?
What files you have there, should work

**Comment by bedna-KU** [comment]
Yes
```
ll checkpoints/
total 34M
-rw-r--r-- 1 mario mario   93 Sep  6 20:50 checkpoint
-rw-r--r-- 1 mario mario  34M Sep  6 20:50 yolov3_custom_Tiny.data-00000-of-00001
-rw-r--r-- 1 mario mario 3.8K Sep  6 20:50 yolov3_custom_Tiny.index
```

**Comment by wzhao82** [comment]
I have the same issue :9

**Comment by bedna-KU** [comment]
I change
```
YOLO_TYPE                   = "yolov3" # yolov4 or yolov3
YOLO_TYPE                   = "yolov4" # yolov4 or yolov3
```
and I have the same problem.

**Comment by robisen1** [comment]
same issue

**Comment by robisen1** [comment]
I have a similar issue.

**Comment by bedna-KU** [comment]
I resolved this issue with:
`yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)`
change to 
`yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)`
on line 29.

I have another issue. In config I have:
`TRAIN_CLASSES               = "tools/dataset/list.names"`
but output is from **model_data/coco/coco.names**

**Comment by bedna-KU** [comment]
Finally :)

I change:
`detect_image(yolo, file, '', input_size=YOLO_INPUT_SIZE, show=True, rectangle_colors=(255,0,0))`
to:
`detect_image(yolo, "data/" + file, "", input_size=YOLO_INPUT_SIZE, show=True, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))`

It can be closed.

**Comment by pythonlessons** [comment]
Nice that you found it out! :)

**Comment by robisen1** [comment]
When I follow Bedna's changes I get "return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'bool' object has no attribute 'endswith'"

**Comment by bedna-KU** [comment]
@robisen1 this issue occurs when change in config:
`TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov4_custom"`
to non-existent file or True.

**Comment by robisen1** [comment]
> @robisen1 this issue occurs when change in config:
> `TRAIN_FROM_CHECKPOINT = False # "checkpoints/yolov4_custom"`
> to True. You have to write the path to the checkpoints e.g.:
> `TRAIN_FROM_CHECKPOINT = "checkpoints/yolov4_custom_Tiny"`

Thanks for the response but I still get errors. Making the change you suggest still results in files like "yolov4_custom_Tiny.data-00000-of-00001" and I still get a error like "return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'bool' object has no attribute 'endswith'" which suggests that the file format or file is incorrect. Any thoughts? I appreciate your assistance.

**Comment by bedna-KU** [comment]
With `TRAIN_FROM_CHECKPOINT = False` work OK, or not?
Please put a config here.

**Comment by robisen1** [comment]
Here is my current config https://pastebin.pl/view/4f020370

**Comment by bedna-KU** [comment]
I don't see any problem.
I change YOLO_TRT_QUANTIZE_MODE      = "INT8" # INT8, FP16, FP32
to
I change YOLO_TRT_QUANTIZE_MODE      = "FP16" # INT8, FP16, FP32
but ...
I'm sorry, you have to wait for someone else

**Comment by bedna-KU** [comment]
I have in config:
```
YOLO_INPUT_SIZE             = 416
TRAIN_INPUT_SIZE            = 416
TEST_INPUT_SIZE             = 416
```
you have 408.

**Comment by robisen1** [comment]
Thanks ill try your suggestions but I am a bit confused. If your training model from scratch the input size should not be a issue. set Alexyab even says "network size width=416 height=416 or any value multiple of 32" https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects and 608 sort a norm for Yolov4 but i will definitely try your suggestion and thank you for your suggestions and help.
