### ISSUE TITLE
Problem with the detection_demo.py (first test)

### ISSUE THREAD

**Issue by LionAaron** [pythonlessons/TensorFlow-2.x-YOLOv3#46]
Hello,
first a big thank you for your tutorial and the repository. They are great.
I cloned your repository, installed the requirements.txt, downloaded the yolov4.weights and changed in configs.py line 13 "yolov3" to "yolov4".

When I started the detection_demo.py the following error occurred:

2020-09-07 07:43:52.622543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:/Users/aaron/Documents/YOLOv4/TensorFlow-2.x-YOLOv3/detection_demo.py", line 15, in <module>
    import tensorflow as tf
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\models.py", line 24, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\metrics.py", line 37, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 51, in <module>
    from tensorflow.python.keras import initializers
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\initializers\__init__.py", line 127, in <module>
    populate_deserializable_objects()
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\initializers\__init__.py", line 85, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

**Comment by pythonlessons** [comment]
I think it's something wrong with your tensorflow version. I updated the requirements file, can you try installing tensorflow==2.3.0 or tensorflow-gpu==2.3.0

**Comment by LionAaron** [comment]
Thank you so much, it works!
