### ISSUE TITLE
GPU not loading during training

### ISSUE THREAD

**Issue by naitfox** [pythonlessons/TensorFlow-2.x-YOLOv3#48]
So earlier I was getting the same issue from issue #45 
 E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR
_NO_DEVICE: no CUDA-capable device is detected

Here is my sytem config for reference:
Ubuntu 18.04 LTS
i7- 9th GEN
GTX 1660 Ti 6GB (notebook)
16 GB RAM
CUDA Toolkit - 10.1.243
cudnn - 7.6.5
Driver version 450.66 (It doesnt work with r418 either)
No other programs running in background
I tried the fix reccomened by FussnerS and am now getting a new error.

swastik@G531G:~/Documents/TensorFlow-2.x-YOLOv3$ python train.py
2020-09-09 11:24:28.420718: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-09-09 11:24:28.445247: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2599990000 Hz
2020-09-09 11:24:28.445783: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564df49d7b30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-09 11:24:28.445815: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-09 11:24:28.446370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-09 11:24:28.458470: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.458703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 268.26GiB/s
2020-09-09 11:24:28.458815: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 11:24:28.459771: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-09 11:24:28.460699: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-09 11:24:28.460898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-09 11:24:28.461914: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-09 11:24:28.462462: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-09 11:24:28.464652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 11:24:28.464724: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.465068: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.465261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-09 11:24:28.465282: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 11:24:28.519237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-09 11:24:28.519280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-09 11:24:28.519296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-09 11:24:28.519459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.519734: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.519970: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.520200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/device:GPU:0 with 5052 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-09 11:24:28.521529: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564df7fd1160 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-09 11:24:28.521541: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1660 Ti, Compute Capability 7.5
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 2658484180504880421
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 12809034059942815785
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 5298053440
locality {
  bus_id: 1
  links {
  }
}
incarnation: 11980719283488140266
physical_device_desc: "device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 5307793851066346902
physical_device_desc: "device: XLA_GPU device"
]
2020-09-09 11:24:28.522030: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.522225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 268.26GiB/s
2020-09-09 11:24:28.522249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 11:24:28.522257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-09 11:24:28.522264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-09 11:24:28.522273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-09 11:24:28.522281: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-09 11:24:28.522289: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-09 11:24:28.522296: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 11:24:28.522322: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.522517: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.522695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
GPUs [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2020-09-09 11:24:28.572536: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.572786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 268.26GiB/s
2020-09-09 11:24:28.572843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-09-09 11:24:28.572854: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-09-09 11:24:28.572862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-09-09 11:24:28.572888: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-09-09 11:24:28.572920: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-09-09 11:24:28.572942: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-09-09 11:24:28.572950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 11:24:28.572981: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.573183: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.573364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-09-09 11:24:28.573406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-09 11:24:28.573411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-09-09 11:24:28.573415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-09-09 11:24:28.573458: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.573663: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-09 11:24:28.573852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5052 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
skipping conv2d_74
skipping conv2d_66
skipping conv2d_58
2020-09-09 11:24:45.025499: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-09 11:24:45.477260: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-09-09 11:24:45.489178: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 926, in conv2d
    "dilations", dilations)
tensorflow.python.eager.core._FallbackException: Expecting int64_t value for attr strides, got numpy.int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 195, in <module>
    main()
  File "train.py", line 150, in main
    results = train_step(image_data, target)
  File "train.py", line 88, in train_step
    pred_result = yolo(image_data, training=True)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 719, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 888, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 207, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1106, in __call__
    return self.conv_op(inp, filter)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 638, in __call__
    return self.call(inp, filter)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 237, in __call__
    name=self.name)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2014, in conv2d
    name=name)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 933, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1022, in conv2d_eager_fallback
    ctx=ctx, name=name)
  File "/home/swastik/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

.
.
.
Also, I should mention that earlier the model was training on my CPU after showing the error (same as #45 ). Now it just fails.

**Comment by FussnerS** [comment]
See: 
https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/issues/45

Do any of those suggestions solve your problem?

**Comment by naitfox** [comment]
"I tried the fix recommended by FussnerS and am now getting a new error."
I tried your snippet but it gave this new error.

**Comment by pythonlessons** [comment]
Hi, it's quite a strange error. Can you try to change TRAIN_BATCH_SIZE to 1 in configs.py file? Maybe it's not enough memory on gpu card with default (4) batch size

**Comment by wzhao82** [comment]
which cuDNN do you have? it might need to be 7.6.5 to be compatible with TF atm I think

**Comment by naitfox** [comment]
> Hi, it's quite a strange error. Can you try to change TRAIN_BATCH_SIZE to 1 in configs.py file? Maybe it's not enough memory on gpu card with default (4) batch size

Tried that but it did not solve the error. Got the same error. Also I dont think memory runs out on the GPU. Can we look at it from any other angle?

**Comment by naitfox** [comment]
> which cuDNN do you have? it might need to be 7.6.5 to be compatible with TF atm I think

I use 7.6.5. I have added the system details in the question for others too

**Comment by wzhao82** [comment]
Maybe edit: os.environ['CUDA_VISIBLE_DEVICES'] = '0'

**Comment by Myron1996** [comment]
Does anyone knows how to resolve following error 
`Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
`

**Comment by pythonlessons** [comment]
install CudNN 7...

**Comment by Myron1996** [comment]
you mean 7.6.5 ? @pythonlessons

**Comment by pythonlessons** [comment]
> you mean 7.6.5 ? @pythonlessons

yes, because I see you use Cuda 10.1
Tensorflow can't handle Cuda 10.2 and CudNN>7.6.5
Well, it can but there is a lot of errors and etc. easier to use what is working

**Comment by Myron1996** [comment]
I just reinstalled everything but I still have the same error
**CUDA** 
```
mayur@mayur:~/Downloads/TensorFlow-2.x-YOLOv3$ nvcc  --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
**CUDNN**

```
mayur@mayur:~/Downloads/TensorFlow-2.x-YOLOv3$ /sbin/ldconfig -N -v $(sed ‘s/:/ /’ <<< $LD_LIBRARY_PATH) 2>/dev/null | grep libcudnn
sed: -e expression #1, char 1: unknown command: `�'
	libcudnn.so.7 -> libcudnn.so.7.6.5
```
**Error**

```
mayur@mayur:~/Downloads/TensorFlow-2.x-YOLOv3$ sudo python3 train.py 
2020-09-30 12:22:22.857174: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 12:22:23.826231: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-30 12:22:23.850810: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2799925000 Hz
2020-09-30 12:22:23.851290: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x423a070 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-30 12:22:23.851320: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-30 12:22:23.853140: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-30 12:22:23.916168: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 12:22:23.916527: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4264490 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-30 12:22:23.916541: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1050 Ti, Compute Capability 6.1
2020-09-30 12:22:23.916729: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 12:22:23.917040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.62GHz coreCount: 6 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 104.43GiB/s
2020-09-30 12:22:23.917082: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 12:22:23.917250: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-09-30 12:22:23.918490: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-30 12:22:23.918798: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-30 12:22:23.920142: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-30 12:22:23.920934: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-30 12:22:23.923789: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-30 12:22:23.923810: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-09-30 12:22:23.923848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 12:22:23.923869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-30 12:22:23.923875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13117026844981186295
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 16593581443823636729
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 2642544342600149166
physical_device_desc: "device: XLA_GPU device"
]
2020-09-30 12:22:23.937207: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-30 12:22:23.937563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 Ti computeCapability: 6.1
coreClock: 1.62GHz coreCount: 6 deviceMemorySize: 3.95GiB deviceMemoryBandwidth: 104.43GiB/s
2020-09-30 12:22:23.937604: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-30 12:22:23.937724: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2020-09-30 12:22:23.937741: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-30 12:22:23.937772: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-30 12:22:23.937787: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-30 12:22:23.937801: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-30 12:22:23.937833: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-30 12:22:23.937840: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
GPUs []
2020-09-30 12:22:23.938568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 12:22:23.938580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
skipping conv2d_74
skipping conv2d_66
skipping conv2d_58
epoch: 0 step:    2/250, lr:0.000000, giou_loss:  26.15, conf_loss:2083.10, prob_loss: 165.82, total_loss:2275.06
epoch: 0 step:    3/250, lr:0.000001, giou_loss:  17.73, conf_loss:1511.33, prob_loss: 123.47, total_loss:1652.54

```

**Comment by pythonlessons** [comment]
Google errors, its something with installation

**Comment by Myron1996** [comment]
I have two GPU's but when i try to add both of them in **train.py** as below 

```
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
```
I get following **memory growth error** . Full error log is given below 

```
2020-10-03 19:44:35.840181: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-10-03 19:44:35.865548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3499910000 Hz
2020-10-03 19:44:35.866574: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8044000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-03 19:44:35.866608: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-03 19:44:35.868953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-10-03 19:44:36.366485: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x46cb6d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-03 19:44:36.366573: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN RTX, Compute Capability 7.5
2020-10-03 19:44:36.366583: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TITAN RTX, Compute Capability 7.5
2020-10-03 19:44:36.367620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2020-10-03 19:44:36.368268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:68:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2020-10-03 19:44:36.368537: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-03 19:44:36.370673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-03 19:44:36.372529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-10-03 19:44:36.372973: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-10-03 19:44:36.375027: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-10-03 19:44:36.375943: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-10-03 19:44:36.380595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-03 19:44:36.383167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-10-03 19:44:36.383199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-03 19:44:36.384731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-03 19:44:36.384743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1 
2020-10-03 19:44:36.384747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N Y 
2020-10-03 19:44:36.384750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   Y N 
2020-10-03 19:44:36.386752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/device:GPU:0 with 22604 MB memory) -> physical GPU (device: 0, name: TITAN RTX, pci bus id: 0000:1a:00.0, compute capability: 7.5)
2020-10-03 19:44:36.387770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/device:GPU:1 with 22582 MB memory) -> physical GPU (device: 1, name: TITAN RTX, pci bus id: 0000:68:00.0, compute capability: 7.5)
2020-10-03 19:44:36.406752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2020-10-03 19:44:36.407372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:68:00.0 name: TITAN RTX computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 23.65GiB deviceMemoryBandwidth: 625.94GiB/s
2020-10-03 19:44:36.407389: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-03 19:44:36.407395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-03 19:44:36.407401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-10-03 19:44:36.407407: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-10-03 19:44:36.407413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-10-03 19:44:36.407419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-10-03 19:44:36.407425: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-03 19:44:36.409748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 41, in main
    writer = tf.summary.create_file_writer(TRAIN_LOGDIR)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py", line 379, in create_file_writer_v2
    with ops.name_scope(name, "create_file_writer") as scope, ops.device("cpu:0"):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5042, in device
    return context.device(device_name_or_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1920, in device
    ensure_initialized()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1716, in ensure_initialized
    context().ensure_initialized()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 502, in ensure_initialized
    config_str = self.config.SerializeToString()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 958, in config
    gpu_options = self._compute_gpu_options()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1010, in _compute_gpu_options
    raise ValueError("Memory growth cannot differ between GPU devices")
ValueError: Memory growth cannot differ between GPU devices

```

Can you please help me resolve this issue.

**Comment by pythonlessons** [comment]
My code does not support more than one gpu, sorry for that
