### ISSUE TITLE
Failed to convert Alex's darknet custom trained weights !

### ISSUE THREAD

**Issue by 12343954** [pythonlessons/TensorFlow-2.x-YOLOv3#50]
I trained my dataset , generated some weights files， and I use `convert_to_pb.py` to convert my custom weights to *.pb file.

always fail!

using default config with yolov3，`Convert_to_pb.py` always be fine.

```
(tf2_py374) D:\Tensorflow2\darknet\build\darknet\x64\TensorFlow_2.x_YOLOv3>python Convert_to_pb.py
2020-09-12 20:49:24.892145: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-12 20:49:26.573650: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-09-12 20:49:26.594044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.755GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-09-12 20:49:26.597994: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-12 20:49:26.602725: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-09-12 20:49:26.607236: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-09-12 20:49:26.611288: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-09-12 20:49:26.616769: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-09-12 20:49:26.620259: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-09-12 20:49:26.628963: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-09-12 20:49:26.631240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-12 20:49:26.632461: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-12 20:49:26.640920: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a6fc17cf50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-12 20:49:26.643947: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-12 20:49:26.645725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.755GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-09-12 20:49:26.650759: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-09-12 20:49:26.652231: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-09-12 20:49:26.655432: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-09-12 20:49:26.657607: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-09-12 20:49:26.666303: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-09-12 20:49:26.671663: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-09-12 20:49:26.674852: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-09-12 20:49:26.680977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-12 20:49:27.102780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-12 20:49:27.105822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-09-12 20:49:27.107148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-09-12 20:49:27.108402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4594 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-09-12 20:49:27.115270: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a6a1ddc200 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-12 20:49:27.118053: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5
2020-09-12 20:49:28.575087: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open model_data\yolov3_custom_63000\yolov3_custom_63000.weights: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "Convert_to_pb.py", line 38, in <module>
    yolo.load_weights(YOLO_CUSTOM_WEIGHTS)  # use custom weights
  File "D:\Programs\Anaconda3\envs\tf2_py374\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2204, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "D:\Programs\Anaconda3\envs\tf2_py374\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "D:\Programs\Anaconda3\envs\tf2_py374\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```
## config.py
```
YOLO_CUSTOM_WEIGHTS         = "model_data/yolov3_custom_63000/yolov3_custom_63000.weights" # False # "checkpoints/yolov3_custom" # used in evaluate_mAP.py and custom model detection, if not using leave False

TRAIN_CLASSES               = "model_data/yolov3_custom_63000/coco_custom.names" # "mnist/mnist.names"
```

**Comment by pythonlessons** [comment]
You did everything in the following steps:?

### Custom trained YOLO weights:
- Download weights from links above;
- In `configs.py` script choose your `YOLO_TYPE`;
- In `configs.py` script set `YOLO_INPUT_SIZE = 608`;
- Train custom YOLO model with instructions above;
- In `configs.py` script set `YOLO_CUSTOM_WEIGHTS = f"{YOLO_TYPE}_custom"`;
- In `configs.py` script make sure that  `TRAIN_CLASSES` is with your custom classes text file;
- From main directory in terminal type `python tools/Convert_to_pb.py`;
- From main directory in terminal type `python tools/Convert_to_TRT.py`;
- In `configs.py` script set `YOLO_FRAMEWORK = "trt"`;
- In `configs.py` script set `YOLO_CUSTOM_WEIGHTS = f'checkpoints/{YOLO_TYPE}-trt-{YOLO_TRT_QUANTIZE_MODE}–{YOLO_INPUT_SIZE}'`;
- Now you can run `detection_custom.py`, to test custom trained and converted TensorRT model.

**Comment by 12343954** [comment]
no ,  i did these steps.

Download weights from links above;
In configs.py script choose your YOLO_TYPE;
In configs.py script set YOLO_INPUT_SIZE = 608;
Train custom YOLO model with instructions above;
In configs.py script set YOLO_CUSTOM_WEIGHTS = f"{YOLO_TYPE}_custom";
In configs.py script make sure that TRAIN_CLASSES is with your custom classes text file;
From main directory in terminal type python tools/Convert_to_pb.py;

**Comment by pythonlessons** [comment]
Oh, I see now, you are using Alex's darknet custom trained weights.
first, you need to convert this model to TensorFlow model. It's a more tricky situation. I didn't implemented this situation to my code.
You should use load_yolo_weights function with your custom trained model and classes. 
In convert to pb script instead of this:
```
if YOLO_CUSTOM_WEIGHTS == False:
    yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=YOLO_COCO_CLASSES)
    load_yolo_weights(yolo, Darknet_weights) # use Darknet weights
else:
    yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
    yolo.load_weights(YOLO_CUSTOM_WEIGHTS) # use custom weights
```

use following:
```
yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
load_yolo_weights(yolo, YOLO_CUSTOM_WEIGHTS) # use Darknet weights
```

**Comment by 12343954** [comment]
thank you for reply!
i will try!
by the way, i suggest you develop AI under AB's darknet.  it's faster than tensorflow very much !

**Comment by pythonlessons** [comment]
I know, but I develop this for learning purposes, If this would be used for some kind of commercial use I would use AB's darknet. Because it's quite hard to implement AB's darknet detection to custom python code

**Comment by 12343954** [comment]
oh, i think you don't use AB's darknet at all!

actually，i issue is，can i use the AB's weights directly in the deep_sort algorithm. 
i don't want to use tensorflow at all， it's so suck！tooooo slow！

is the `deep_sort algorithm` pure algorithm withou deep learning?

**Comment by pythonlessons** [comment]
I use only weights from darknet. In my implementation, you can't and I think you won't find such implementation where you could use deepsort and AB's darknet without tensorflow. If you need speed while tracking objects with the original darknet you will need to write the whole code by your self, but I might be wrong, you need to do research by your self.

**Comment by 12343954** [comment]
en. ok. i see. thank you for reply!

**Comment by pythonlessons** [comment]
No problem, closing this.

**Comment by afaq-ahmad** [comment]
Facing the same problem with darknet custom train yolov3. 
`
ValueError: Fetch argument <tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("conv2d/kernel/Read/ReadVariableOp:0", shape=(3, 3, 3, 32), dtype=float32) is not an element of this graph.)
`
