### ISSUE TITLE
TRT convertion

### ISSUE THREAD

**Issue by romeolandry** [pythonlessons/TensorFlow-2.x-YOLOv3#61]
Thank you  to share you code with us!

**Comment by romeolandry** [comment]
I downloaded the repo and the weight from yolov3-416. i try to convert the tensorflow frozen graph from this model to TRT but itn's work well.

**Comment by romeolandry** [comment]
Hier is the error a recieved! 

`Traceback (most recent call last):
  File "tools/Convert_to_TRT.py", line 45, in <module>
    converter.convert()
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1087, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1075, in convert_variables_to_constants_v2
    converted_input_indices)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1001, in _construct_concrete_function
    new_output_names)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 628, in wrap_function
    collections={}),
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/kamgo-gpu/.virtualenvs/builded_tf230_TRT/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node StatefulPartitionedCall/model/batch_normalization/AssignNewValue was passed float from Func/StatefulPartitionedCall/input/_4:0 incompatible with expected resource.`

**Comment by romeolandry** [comment]
Sorry for my english!

**Comment by Myron1996** [comment]
Does anyone manage to install Tensorrt on Ubuntu 18.04, CUDA 10.1, Cudnn7 
```
udo apt-get install tensorrt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 tensorrt : Depends: libnvinfer6 (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-plugin6 (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvparsers6 (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvonnxparsers6 (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-bin (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-dev (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-plugin-dev (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvparsers-dev (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvonnxparsers-dev (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-samples (= 6.0.1-1+cuda10.1) but it is not going to be installed
            Depends: libnvinfer-doc (= 6.0.1-1+cuda10.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
