### ISSUE TITLE
Tensorflow error while trying to train

### ISSUE THREAD

**Issue by ezratoga** [pythonlessons/TensorFlow-2.x-YOLOv3#70]
I'm trying to python train.py on my cmd, but there was this error message:

Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from tensorflow.python.client import device_lib
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

 I hope there will be the right respon fast. Thanks before

**Comment by pythonlessons** [comment]
what OS you have?
What TensorFlow version you have, you sure TensorFlow is working properly?

**Comment by ezratoga** [comment]
my os is windows 10
tensorflow 2.3.0. it works propely always

**Comment by pythonlessons** [comment]
> my os is windows 10
> tensorflow 2.3.0. it works propely always

That's strange. 
Can you try a solution from this [link](https://github.com/tensorflow/tensorflow/issues/35749):
1.https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
2. download x64: vc_redist.x64.exe
3.install it.

**Comment by ezratoga** [comment]
> > my os is windows 10
> > tensorflow 2.3.0. it works propely always
> 
> That's strange.
> Can you try a solution from this [link](https://github.com/tensorflow/tensorflow/issues/35749):
> 1.https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
> 2. download x64: vc_redist.x64.exe
> 3.install it.

thx for help. but there's a new problem. the train always len(testset) always = 0. because the output on cmd only "configure TEST options to validate model"

**Comment by pythonlessons** [comment]
Do you have test dataset?

**Comment by ezratoga** [comment]
> Do you have test dataset?

yes i do

![image_2020-10-28_103731](https://user-images.githubusercontent.com/67219628/97387920-95967e00-1909-11eb-9ecd-814df9b2fef9.png)

**Comment by ezratoga** [comment]
![image_2020-10-28_104757](https://user-images.githubusercontent.com/67219628/97388614-0a1dec80-190b-11eb-9d7f-d213c0db8573.png)

this is the output of cmd

**Comment by pythonlessons** [comment]
did you configured your test dataset in configs.py? Because the model can't see that
