### ISSUE TITLE
Issue in evaluate_mAP.py

### ISSUE THREAD

**Issue by ashraf-rashid** [pythonlessons/TensorFlow-2.x-YOLOv3#72]
I get the following error while running train.py for mnist data:

Traceback (most recent call last):
  File "train.py", line 186, in <module>
    main()
  File "train.py", line 75, in main
    get_mAP(t, testset, score_threshold=TEST_SCORE_THRESHOLD, iou_threshold=TEST_IOU_THRESHOLD)
  File "D:\Imran_Razzak\new - Yolo v3 - tf 2.0\TensorFlow-2.x-YOLOv3-master\evaluate_mAP.py", line 154, in get_mAP
    pred_bbox = tf.concat(pred_bbox, axis=0)
  File "C:\ProgramData\Anaconda3\envs\tf2_test_install\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2_test_install\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1654, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\ProgramData\Anaconda3\envs\tf2_test_install\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1207, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\ProgramData\Anaconda3\envs\tf2_test_install\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [676,45] vs. shape[1] = [2028,15] [Op:ConcatV2] name: concat

I'm using the tiny yolo pretrained weights.

Here's the only extra lines I have added in the code:

After loading the tiny 
t = tf.keras.models.load_model('temp.hdf5')
get_mAP(t, testset, score_threshold=TEST_SCORE_THRESHOLD, iou_threshold=TEST_IOU_THRESHOLD)

**Comment by pythonlessons** [comment]
Didn't tried to save and load the model as .h5, but it seems that it has a mismatch with classes of what your model has and what you try to predict

**Comment by vaan2010** [comment]
This error is about training option is True or False in Create_Yolo function, when you inference the model, you should change the training option to False, when you are in training, change training option to True.
