### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by julio8a** [pythonlessons/TensorFlow-2.x-YOLOv3#75]
I followed the tutorial to build a custom model here:
https://pylessons.com/YOLOv3-TF2-custrom-images/

However, I'm getting this error. Any help or direction would be greatly appreciated.

```
ValueError: Dimension 1 in both shapes must be equal, but are 20 and 26. Shapes are [4,20,20] and [4,26,26]. for '{{node concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _cloned=true](inputs, inputs_1, concat/axis)' with input shapes: [4,20,20,128], [4,26,26,256], [] and with computed input tensors: input[2] = <-1>
```

**Comment by julio8a** [comment]
I added my class name to coco.names and it solved that error, but now I'm facing this value error:

`ValueError: cannot reshape array of size 63738 into shape (258,256,1,1)`

**Comment by julio8a** [comment]
commented out assert line in `yolov3/utils.py` and I got rid of the last error. 
However, I'm back to the 

```
ValueError: Dimension 1 in both shapes must be equal, but are 20 and 26. Shapes are [4,20,20] and [4,26,26]. for '{{node concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _cloned=true](inputs, inputs_1, concat/axis)' with input shapes: [4,20,20,128], [4,26,26,256], [] and with computed input tensors: input[2] = <-1>
```

**Comment by julio8a** [comment]
Keep trying to figure out, sorry for all the comments. I'm on a new error now:

```
python train.py 
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18020096477832167469
]
GPUs []
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 53, in main
    load_yolo_weights(Darknet, Darknet_weights) # use darknet weights
  File "/home/pi/TensorFlow-2.x-YOLOv3/yolov3/utils.py", line 66, in load_yolo_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 62196 into shape (261,256,1,1)
```

**Comment by julio8a** [comment]
Got it working. I did some other tutorial you posted and had changed the input size. Reverted commit to default 416 and it's working...

**Comment by pythonlessons** [comment]
Nice to Hear!
