### ISSUE TITLE
UnboundLocalError: local variable 'label_sbbox' referenced before assignment

### ISSUE THREAD

**Issue by PonraJS-21** [pythonlessons/TensorFlow-2.x-YOLOv3#94]
UnboundLocalError: local variable 'label_sbbox' referenced before assignment

The mentioned error occur while i am using my own labled data. What may br the reason.
Note: I use labelimg for windows executable file from https://tzutalin.github.io/labelImg/ link

**Comment by pythonlessons** [comment]
I don't know... didn't faced such error

**Comment by PonraJS-21** [comment]
Deleting ['D:\\Education Content\\Dev Tools\\Python\\Python_Project\\YOLO\\TensorFlow-2.x-YOLOv3-master/Rice_dataset/train/IMG_20201120_132040.jpg', ['459,622,850,951,1', '1224,635,1633,1018,1', '2779,1725,3153,2009,1', '2717,2173,3040,2412,1', '2140,170,2504,499,1', '2969,473,3214,741,1', '427,1531,830,1922,1', '1982,2338,2301,2564,1', '1030,1815,1346,2241,1', '3791,1664,3982,1880,1', '14,1918,156,2209,1', '11,1183,140,1476,1', '2075,1660,2498,2254,0', '1627,873,2062,1341,0', '1053,67,1556,412,0', '24,244,375,731,0', '898,1096,1227,1667,0'], array([[[181, 183, 184],
        [181, 183, 184],
        [181, 183, 184],
        ...,
        [181, 186, 187],
        [180, 185, 186],
        [179, 184, 185]],

       [[180, 182, 183],
        [180, 182, 183],
        [180, 182, 183],
        ...,
        [184, 189, 190],
        [182, 187, 188],
        [180, 185, 186]],

       [[180, 182, 183],
        [180, 182, 183],
        [180, 182, 183],
        ...,
        [187, 192, 193],
        [184, 189, 190],
        [183, 188, 189]],

       ...,

       [[149, 151, 152],
        [150, 152, 153],
        [150, 152, 153],
        ...,
        [150, 152, 152],
        [150, 152, 152],
        [150, 152, 152]],

       [[151, 153, 154],
        [151, 153, 154],
        [151, 153, 154],
        ...,
        [152, 154, 154],
        [151, 153, 153],
        [151, 153, 153]],

       [[152, 154, 155],
        [152, 154, 155],
        [151, 153, 154],
        ...,
        [154, 156, 156],
        [152, 154, 154],
        [152, 154, 154]]], dtype=uint8)] annotation line
IndexError, something wrong with D:\Education Content\Dev Tools\Python\Python_Project\YOLO\TensorFlow-2.x-YOLOv3-master/Rice_dataset/train/IMG_20201120_132040.jpg removed this line from annotation file
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 138, in main
    for image_data, target in trainset:
  File "D:\Education Content\Dev Tools\Python\Python_Project\YOLO\TensorFlow-2.x-YOLOv3-master\yolov3\dataset.py", line 123, in __next__
    batch_label_sbbox[num, :, :, :, :] = label_sbbox
UnboundLocalError: local variable 'label_sbbox' referenced before assignment

**May be this happens because of predicted bound is not in the image?**

**Comment by pythonlessons** [comment]
Yes, this happens because of some kind of bad annotation, as you can see my code should have deleted that bad image for you
